# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1251, 823)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.current_query = QtWidgets.QLabel(self.centralwidget)
        self.current_query.setGeometry(QtCore.QRect(180, 0, 651, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.current_query.setFont(font)
        self.current_query.setWordWrap(True)
        self.current_query.setObjectName("current_query")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(840, 0, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.current_index = QtWidgets.QLabel(self.centralwidget)
        self.current_index.setGeometry(QtCore.QRect(980, 0, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.current_index.setFont(font)
        self.current_index.setObjectName("current_index")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 590, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.last_case_view = QtWidgets.QLabel(self.centralwidget)
        self.last_case_view.setGeometry(QtCore.QRect(180, 540, 441, 141))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.last_case_view.setFont(font)
        self.last_case_view.setWordWrap(True)
        self.last_case_view.setObjectName("last_case_view")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.case_title = QtWidgets.QLabel(self.centralwidget)
        self.case_title.setGeometry(QtCore.QRect(180, 70, 1011, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.case_title.setFont(font)
        self.case_title.setWordWrap(True)
        self.case_title.setObjectName("case_title")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(630, 230, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(56, 690, 569, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.last_query_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.last_query_btn.setFont(font)
        self.last_query_btn.setObjectName("last_query_btn")
        self.horizontalLayout.addWidget(self.last_query_btn)
        self.last_case_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.last_case_btn.setFont(font)
        self.last_case_btn.setObjectName("last_case_btn")
        self.horizontalLayout.addWidget(self.last_case_btn)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(640, 570, 551, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yes_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.yes_btn.setFont(font)
        self.yes_btn.setObjectName("yes_btn")
        self.horizontalLayout_2.addWidget(self.yes_btn)
        self.soso_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.soso_btn.setFont(font)
        self.soso_btn.setObjectName("soso_btn")
        self.horizontalLayout_2.addWidget(self.soso_btn)
        self.no_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.no_btn.setFont(font)
        self.no_btn.setObjectName("no_btn")
        self.horizontalLayout_2.addWidget(self.no_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.save_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.save_btn.setFont(font)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout.addWidget(self.save_btn)
        self.select_file_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.select_file_btn.setFont(font)
        self.select_file_btn.setObjectName("select_file_btn")
        self.verticalLayout.addWidget(self.select_file_btn)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(60, 270, 1131, 251))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.content = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.content.setFont(font)
        self.content.setObjectName("content")
        self.horizontalLayout_3.addWidget(self.content)
        self.viewpoint = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.viewpoint.setFont(font)
        self.viewpoint.setObjectName("viewpoint")
        self.horizontalLayout_3.addWidget(self.viewpoint)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 150, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.case_cause = QtWidgets.QLabel(self.centralwidget)
        self.case_cause.setGeometry(QtCore.QRect(180, 140, 1011, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.case_cause.setFont(font)
        self.case_cause.setWordWrap(True)
        self.case_cause.setObjectName("case_cause")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1251, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.yes_btn.clicked.connect(MainWindow.set_yes)
        self.soso_btn.clicked.connect(MainWindow.set_soso)
        self.no_btn.clicked.connect(MainWindow.set_no)
        self.save_btn.clicked.connect(MainWindow.save)
        self.select_file_btn.clicked.connect(MainWindow.select_file)
        self.last_query_btn.clicked.connect(MainWindow.last_query)
        self.last_case_btn.clicked.connect(MainWindow.last_case)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "当前问题:"))
        self.current_query.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "当前索引:"))
        self.current_index.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "上一个案件:"))
        self.last_case_view.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "案件标题:"))
        self.case_title.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "案件内容"))
        self.label_4.setText(_translate("MainWindow", "法院观点"))
        self.last_query_btn.setText(_translate("MainWindow", "上一个问题"))
        self.last_case_btn.setText(_translate("MainWindow", "上一个案件(U)"))
        self.yes_btn.setText(_translate("MainWindow", "正确(1)"))
        self.soso_btn.setText(_translate("MainWindow", "相关(2)"))
        self.no_btn.setText(_translate("MainWindow", "错误(3)"))
        self.save_btn.setText(_translate("MainWindow", "保存(s)"))
        self.select_file_btn.setText(_translate("MainWindow", "选择文件"))
        self.label_8.setText(_translate("MainWindow", "当前案由:"))
        self.case_cause.setText(_translate("MainWindow", "TextLabel"))

