# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1251, 823)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.current_query = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.current_query.setFont(font)
        self.current_query.setWordWrap(True)
        self.current_query.setObjectName("current_query")
        self.gridLayout.addWidget(self.current_query, 0, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.current_index = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.current_index.setFont(font)
        self.current_index.setObjectName("current_index")
        self.gridLayout.addWidget(self.current_index, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.case_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.case_title.setFont(font)
        self.case_title.setWordWrap(True)
        self.case_title.setObjectName("case_title")
        self.gridLayout.addWidget(self.case_title, 1, 1, 1, 4)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.case_cause = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.case_cause.setFont(font)
        self.case_cause.setWordWrap(True)
        self.case_cause.setObjectName("case_cause")
        self.gridLayout.addWidget(self.case_cause, 2, 1, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.content = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.content.setFont(font)
        self.content.setObjectName("content")
        self.horizontalLayout_3.addWidget(self.content)
        self.viewpoint = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.viewpoint.setFont(font)
        self.viewpoint.setObjectName("viewpoint")
        self.horizontalLayout_3.addWidget(self.viewpoint)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 5)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.last_case_view = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.last_case_view.setFont(font)
        self.last_case_view.setWordWrap(True)
        self.last_case_view.setObjectName("last_case_view")
        self.gridLayout.addWidget(self.last_case_view, 5, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yes_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.yes_btn.setFont(font)
        self.yes_btn.setObjectName("yes_btn")
        self.horizontalLayout_2.addWidget(self.yes_btn)
        self.soso_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.soso_btn.setFont(font)
        self.soso_btn.setObjectName("soso_btn")
        self.horizontalLayout_2.addWidget(self.soso_btn)
        self.no_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.no_btn.setFont(font)
        self.no_btn.setObjectName("no_btn")
        self.horizontalLayout_2.addWidget(self.no_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.save_btn.setFont(font)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout.addWidget(self.save_btn)
        self.select_file_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.select_file_btn.setFont(font)
        self.select_file_btn.setObjectName("select_file_btn")
        self.verticalLayout.addWidget(self.select_file_btn)
        self.gridLayout.addLayout(self.verticalLayout, 5, 2, 2, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.last_query_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.last_query_btn.setFont(font)
        self.last_query_btn.setObjectName("last_query_btn")
        self.horizontalLayout.addWidget(self.last_query_btn)
        self.last_case_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.last_case_btn.setFont(font)
        self.last_case_btn.setObjectName("last_case_btn")
        self.horizontalLayout.addWidget(self.last_case_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1251, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.yes_btn.clicked.connect(MainWindow.set_yes)
        self.soso_btn.clicked.connect(MainWindow.set_soso)
        self.no_btn.clicked.connect(MainWindow.set_no)
        self.save_btn.clicked.connect(MainWindow.save)
        self.select_file_btn.clicked.connect(MainWindow.select_file)
        self.last_query_btn.clicked.connect(MainWindow.last_query)
        self.last_case_btn.clicked.connect(MainWindow.last_case)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "当前问题:"))
        self.current_query.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "当前索引:"))
        self.current_index.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "案件标题:"))
        self.case_title.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "当前案由:"))
        self.case_cause.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "案件内容"))
        self.label_4.setText(_translate("MainWindow", "法院观点"))
        self.label_5.setText(_translate("MainWindow", "上一个案件:"))
        self.last_case_view.setText(_translate("MainWindow", "TextLabel"))
        self.yes_btn.setText(_translate("MainWindow", "正确(1)"))
        self.soso_btn.setText(_translate("MainWindow", "相关(2)"))
        self.no_btn.setText(_translate("MainWindow", "错误(3)"))
        self.save_btn.setText(_translate("MainWindow", "保存(S)"))
        self.select_file_btn.setText(_translate("MainWindow", "选择文件"))
        self.last_query_btn.setText(_translate("MainWindow", "上一个问题"))
        self.last_case_btn.setText(_translate("MainWindow", "上一个案件(U)"))

